### ISSUE TITLE
Mega task to add Vc hours tracking to thonk bot

### ISSUE THREAD

**Issue by TheIceCreamBear** [TheIceCreamBear/ThonkBot#1]
## Bot State changes
- [x] #2
- [ ] #4
- [ ] #5
- [ ] #6

## Data display
- [ ] Implement http rest api to get data from long term
- [ ] Implement web page to display data
- [ ] Implement simple auth to prevent responding to http calls
- [ ] Provide one time url generator to users via slash command
